// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjWxvvL9Ninu4MgPw6qfEXjIttJLPrLw4',
    appId: '1:649754352379:web:12e83fe702913cf0216e5e',
    messagingSenderId: '649754352379',
    projectId: 'danentang-76245',
    authDomain: 'danentang-76245.firebaseapp.com',
    storageBucket: 'danentang-76245.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaHr-9b5_VtODifC2WiO-BuXYhkEU4i_c',
    appId: '1:649754352379:android:21c5a71d7def4b7f216e5e',
    messagingSenderId: '649754352379',
    projectId: 'danentang-76245',
    storageBucket: 'danentang-76245.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_lJuMjqU9QwPbhz50zjGGKhXBZIwz3nQ',
    appId: '1:649754352379:ios:b95456575d5f399d216e5e',
    messagingSenderId: '649754352379',
    projectId: 'danentang-76245',
    storageBucket: 'danentang-76245.firebasestorage.app',
    iosBundleId: 'com.example.midterm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_lJuMjqU9QwPbhz50zjGGKhXBZIwz3nQ',
    appId: '1:649754352379:ios:b95456575d5f399d216e5e',
    messagingSenderId: '649754352379',
    projectId: 'danentang-76245',
    storageBucket: 'danentang-76245.firebasestorage.app',
    iosBundleId: 'com.example.midterm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjWxvvL9Ninu4MgPw6qfEXjIttJLPrLw4',
    appId: '1:649754352379:web:650bb79c5ce9e236216e5e',
    messagingSenderId: '649754352379',
    projectId: 'danentang-76245',
    authDomain: 'danentang-76245.firebaseapp.com',
    storageBucket: 'danentang-76245.firebasestorage.app',
  );
}
